name: Build OpenWrt images

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    # # only push on new version tags
    # branches:
    #   - main
    tags:
      - "v*"

jobs:
  build-openwrt-images:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix develop .#openwrt-ci --command bash {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: prepare source
        run: |
          git config --global user.name "MayNiklas"
          git config --global user.email "info@niklas-steffen.de"
          git submodule update --init --recursive

      - name: prepare OpenWrt feeds
        run: |
          openwrt/scripts/feeds update -a
          openwrt/scripts/feeds install -a

      - name: copy OpenWrt config
        run: |
          cp targets/Broadcom\ BCM2711/diffconfig openwrt/.config
          cp -r files openwrt/

      - name: prepare OpenWrt config
        run: |
          cd openwrt
          make defconfig

      - name: make download - Broadcom BCM2711
        run: |
          cd openwrt
          make -j$(nproc) download V=s

      - name: make - Broadcom BCM2711
        run: |
          cd openwrt
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Pi-CM4-DUAL-ETH-MINI
          path: |
            /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/*
            !/home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/*/*/packages/

      - name: gh release create ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/*
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${GITHUB_REF#refs/*/}
          gh release upload ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/bcm27xx/bcm2711/config.buildinfo
          gh release upload ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/bcm27xx/bcm2711/feeds.buildinfo
          gh release upload ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/bcm27xx/bcm2711/*.img.gz
          gh release upload ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/bcm27xx/bcm2711/*.tar.gz
          gh release upload ${GITHUB_REF#refs/*/} /home/runner/work/openwrt-pi-cm4/openwrt-pi-cm4/openwrt/bin/targets/bcm27xx/bcm2711/*.manifest
