name: Build OpenWrt images

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-openwrt-images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext \
          git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget

          # set timezoen
          sudo timedatectl set-timezone Europe/Berlin

          # preare workdir
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Checkout OpenWrt and prepare OpenWrt feeds
        run: |
          git clone https://github.com/openwrt/openwrt.git /workdir/openwrt
          cd /workdir/openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build OpenWrt - Pi-CM4-DUAL-ETH-MINI
        run: |
          cd /workdir/openwrt
          cp /home/runner/work/build-openwrt/build-openwrt/targets/Pi-CM4-DUAL-ETH-MINI.config .config
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: openwrt
          path: |
            /workdir/openwrt/bin/targets/*
            !/workdir/openwrt/bin/targets/packages/
