name: Build OpenWrt images

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    tags:
      - "v*"

jobs:
  build-openwrt-images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install build-essential clang flex g++ gawk gcc-multilib gettext \
          git libncurses5-dev libssl-dev python3-distutils rsync unzip gzip zlib1g-dev \
          file wget
          # set timezoen
          sudo timedatectl set-timezone Europe/Berlin
          # preare workdir
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Checkout OpenWrt
        env:
          version: v22.03.2
        run: |
          if [[ "${GITHUB_REF#refs/*/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Checkout OpenWrt version ${GITHUB_REF#refs/*/}"
            git clone --branch ${GITHUB_REF#refs/*/} https://github.com/openwrt/openwrt.git /workdir/openwrt
          else
            echo "Checkout OpenWrt version $version"
            git clone --branch $version https://github.com/openwrt/openwrt.git /workdir/openwrt
          fi

      - name: prepare OpenWrt feeds
        run: |
          /workdir/openwrt/scripts/feeds update -a
          /workdir/openwrt/scripts/feeds install -a

      - name: copy OpenWrt config
        run: |
          cp /home/runner/work/build-openwrt/build-openwrt/targets/Broadcom\ BCM2711/diffconfig /workdir/openwrt/.config

      - name: prepare OpenWrt config
        working-directory: /workdir/openwrt
        run: |
          make defconfig

      - name: Build OpenWrt - Broadcom BCM2711
        working-directory: /workdir/openwrt
        run: |
          make -j$(nproc) download V=s
          make -j$(nproc) V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Pi-CM4-DUAL-ETH-MINI
          path: |
            /workdir/openwrt/bin/targets/*
            !/workdir/openwrt/bin/targets/*/packages/
