name: Build OpenWrt images

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-openwrt-images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: build docker image
        run: docker build -t build-openwrt .

      - name: build openwrt
        run: docker run -v $(pwd)/output:/output build-openwrt

      # - name: list ./output/*
      #   run: ls -al ./output

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: OpenWRT-Pi-CM4-DUAL-ETH-MINI-${GITHUB_REF#refs/*/}
      #     path: |
      #       ./output/*
